package com.mycompany.martin.modelo;
// Generated 8/02/2019 06:39:04 PM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private Usuario usuario;
     private double latitud;
     private double longitud;
     private String descripcion;

    public Marcador() {
    }

	
    public Marcador(int idmarcador, Usuario usuario, double latitud, double longitud) {
        this.idmarcador = idmarcador;
        this.usuario = usuario;
        this.latitud = latitud;
        this.longitud = longitud;
    }
    public Marcador(int idmarcador, Usuario usuario, double latitud, double longitud, String descripcion) {
       this.idmarcador = idmarcador;
       this.usuario = usuario;
       this.latitud = latitud;
       this.longitud = longitud;
       this.descripcion = descripcion;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


